/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/add-fish` | `/add-fish`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/fish-detail` | `/fish-detail`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/list` | `/list`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-records` | `/my-records`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/wagyu-detail` | `/wagyu-detail`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/add-fish` | `/add-fish`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/fish-detail` | `/fish-detail`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/list` | `/list`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/my-records` | `/my-records`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/wagyu-detail` | `/wagyu-detail`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/add-fish${`?${string}` | `#${string}` | ''}` | `/add-fish${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/fish-detail${`?${string}` | `#${string}` | ''}` | `/fish-detail${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/list${`?${string}` | `#${string}` | ''}` | `/list${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/my-records${`?${string}` | `#${string}` | ''}` | `/my-records${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/wagyu-detail${`?${string}` | `#${string}` | ''}` | `/wagyu-detail${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/add-fish` | `/add-fish`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/fish-detail` | `/fish-detail`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/list` | `/list`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-records` | `/my-records`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/wagyu-detail` | `/wagyu-detail`; params?: Router.UnknownInputParams; };
    }
  }
}
